import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "../lib/utils";
import "./globals.css";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased ",
          fontSans.variable
        )}
      >
        <nav className="flex h-full w-full bg-rose-600 px-10 py-10 items-center justify-center">
          <h1 className="text-5xl font-extrabold text-center text-slate-100 max-w-xl">
            Who&apos;s Funding War Crimes?
          </h1>
        </nav>

          {children}

      </body>
    </html>
  );
}
